'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Isla_Delphiino.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CafeCn() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CafeCn", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CafeKr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CafeKr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CafeStd() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CafeStd", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property CafeTw() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CafeTw", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DFHeiE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DFHeiE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_NewRodin_Pro_B() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_NewRodin_Pro_B", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_NewRodin_Pro_DB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_NewRodin_Pro_DB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_NewRodin_Pro_EB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_NewRodin_Pro_EB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_NewRodin_Pro_L() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_NewRodin_Pro_L", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_NewRodin_Pro_M() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_NewRodin_Pro_M", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_NewRodin_Pro_UB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_NewRodin_Pro_UB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_RodinBokutoh_Pro_B() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_RodinBokutoh_Pro_B", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_RodinBokutoh_Pro_DB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_RodinBokutoh_Pro_DB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_RodinBokutoh_Pro_EB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_RodinBokutoh_Pro_EB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_RodinBokutoh_Pro_L() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_RodinBokutoh_Pro_L", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_RodinBokutoh_Pro_M() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_RodinBokutoh_Pro_M", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property FOT_RodinBokutoh_Pro_UB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FOT_RodinBokutoh_Pro_UB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Nintendo_DS_BIOS() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Nintendo_DS_BIOS", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property nintendo_ext_003() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nintendo_ext_003", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property nintendo_ext_LE_003() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nintendo_ext_LE_003", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property nintendo_NTLG_DB_001() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nintendo_NTLG_DB_001", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property nintendo_udsg_r_std_003() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nintendo_udsg_r_std_003", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RodinBokutohPro_B() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RodinBokutohPro_B", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RodinBokutohPro_DB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RodinBokutohPro_DB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RodinBokutohPro_EB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RodinBokutohPro_EB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RodinBokutohPro_L() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RodinBokutohPro_L", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RodinBokutohPro_M() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RodinBokutohPro_M", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RodinBokutohPro_UB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RodinBokutohPro_UB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SQR721N() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SQR721N", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property super_smash_4_1_by_pokemon_diamond_d7zxu6d() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("super_smash_4_1_by_pokemon_diamond_d7zxu6d", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemBottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemButtonHighlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemButtonHighlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemCurrentPage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemCurrentPage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemMajorOption() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemMajorOption", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemNavigationButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemNavigationButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemOtherPage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemOtherPage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemPrevious() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemPrevious", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property systemTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("systemTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
